export const keys = [
  { value: "C", label: "C", type: "action"},
  { label: "-/+", type: "action" },
  { label: "%", type: "action" },
  { label: "DEL", type: "action" },
  { value: 7, label: "7", type: "numeric" },
  { value: 8, label: "8", type: "numeric" },
  { value: 9, label: "9", type: "numeric" },
  { value: "/", label: "/", type: "operation" },
  { value: 4, label: "4", type: "numeric" },
  { value: 5, label: "5", type: "numeric" },
  { value: 6, label: "6", type: "numeric" },
  { value: "*", label: "X", type: "operation" },
  { value: 1, label: "1", type: "numeric" },
  { value: 2, label: "2", type: "numeric" },
  { value: 3, label: "3", type: "numeric" },
  { value: "-", label: "-", type: "operation" },
  { value: 0, label: "0", type: "numeric" },
  { value: ".", label: ".", type: "numeric" },
  { value: "=", label: "=", type: "action" },
  { value: "+", label: "+", type: "operation" },
];
